CREATE TABLE IF NOT EXISTS blogs (
  id SERIAL PRIMARY KEY,
  reference VARCHAR (10) UNIQUE NOT NULL,
  title VARCHAR (50) NOT NULL,
  body TEXT NOT NULL,
  image VARCHAR,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);