CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  reference VARCHAR (10) UNIQUE NOT NULL,
  name VARCHAR (50) NOT NULL,
  email VARCHAR (50) UNIQUE NOT NULL,
  password VARCHAR (100),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_reference ON users(reference);